### PR TITLE
fix(try): pass error into matcher

### PR DESCRIPTION
**Pull request by splodingsocks**
fix(try): pass error into matcher

Pass a Try's error into the Failed case on a match.

Closes https://github.com/jiaweihli/monapt/issues/15.

### CODE REVIEW

**Comment by jiaweihli** [comment]
Looks good - I missed this during the 1.0 migration.  I'll also add some tests for this later.

Can you format your commit message in [conventional style](https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-angular/convention.md)?  e.g. `fix(try): pass error into matcher`.  I'm trying out another tool, [semantic-release](https://github.com/semantic-release/semantic-release), that automatically parses commit messages and generates a changelog/release/npm version.  It'd be neat to see if it works out end-to-end.

**Comment by splodingsocks** [comment]
Sure thing!

**Comment by jiaweihli** [comment]
Sorry, that was unclear.  I meant the commit itself (and then update the PR with `git push -f origin`) rather than the PR description.

Also, can you remove the `BREAKING CHANGE`?  That'll unfortunately cause a major version bump to 2.0.0.  

If this is too much trouble, let me know.  The last thing I want is for PRs to be tedious.  I'm working on integrating tooling to help automate all of this.

**Comment by splodingsocks** [comment]
Oh okay! No that'll be fine 😊. I'll just have to do it late tonight or tomorrow when I'm not only on my phone.

**Comment by jiaweihli** [comment]
No problem - thanks for working through this with me. 👍 

Happy to hear you're getting value out of monapt!

**Comment by splodingsocks** [comment]
No problem! Thanks for being quick to respond. I've updated the commit message now and taken out the BREAKING CHANGE line.

**Comment by jiaweihli** [comment]
Perfect, landed [on npm](https://www.npmjs.com/package/monapt) and released with a [changelog](https://github.com/jiaweihli/monapt/releases/tag/v1.0.3).

**Comment by splodingsocks** [comment]
Also, sorry I didn't add a test for this. I'd like to be better at that in the future. 😅

**Comment by jiaweihli** [comment]
No worries - tests are very much appreciated but I know they're time-consuming to write.

Looks like I need to tweak the code coverage though... 😛

**Pull request merged**
